# Generated by Django 3.2.3 on 2022-08-08 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=30, verbose_name='kraj')),
                ('province', models.CharField(choices=[('1', 'dolnośląskie'), ('2', 'kujawsko-pomorskie'), ('3', 'łódzkie'), ('4', 'lubelskie'), ('5', 'lubuskie'), ('6', 'małopolskie'), ('7', 'mazowieckie'), ('8', 'opolskie'), ('9', 'podkarpackie'), ('10', 'podlaskie'), ('11', 'pomorskie'), ('12', 'śląskie'), ('13', 'świętokrzyskie'), ('14', 'warmińsko-mazurskie'), ('15', 'wielkopolskie'), ('16', 'zachodniopomorskie')], max_length=30, verbose_name='województwo')),
                ('county', models.CharField(max_length=30, verbose_name='powiat')),
                ('commune', models.CharField(max_length=30, verbose_name='gmina')),
                ('city', models.CharField(max_length=30, verbose_name='miasto')),
                ('street_name', models.CharField(max_length=30, verbose_name='ulica')),
                ('street_number', models.CharField(max_length=4, verbose_name='numer budynku')),
                ('room_number', models.CharField(max_length=4, verbose_name='numer lokalu')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, verbose_name='company name')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='imię')),
                ('last_name', models.CharField(max_length=30, verbose_name='nazwisko')),
                ('position', models.CharField(max_length=120, verbose_name='stanowisko')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='telefon służbowy')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='business email')),
                ('related_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.company', verbose_name='pracownik firmy')),
                ('related_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='użytkownik')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('retail', 'retail'), ('company', 'company')], max_length=10, verbose_name='rodzaj')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='account.company', verbose_name='klient firmy')),
                ('related_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='account.company', verbose_name='firma')),
                ('related_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='użytkownik')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=12, verbose_name='NIP')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='telefon kontaktowy')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.address', verbose_name='adres')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.contact', verbose_name='dane kontaktowe'),
        ),
        migrations.AddField(
            model_name='company',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='właściciel'),
        ),
    ]
