# Generated by Django 3.2.3 on 2021-06-24 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobprogress', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobprogress.jobtemplate', verbose_name='typ pracy'),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[], max_length=20, verbose_name='aktualny etap'),
        ),
    ]
