# Generated by Django 3.2.3 on 2021-06-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobprogress', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('1', 'Mapa do celów projektowych'), ('2', 'Wznowienie granic')], max_length=30, verbose_name='rodzaj pracy'),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('1', 'złożenie zgłoszenia w PODGiK'), ('2', 'oczekiwanie na wydanie materiałów')], default=[0], max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='status',
            name='body',
            field=models.TextField(blank=True, max_length=120, null=True, verbose_name='opis'),
        ),
        migrations.RemoveField(
            model_name='status',
            name='job_template',
        ),
        migrations.AddField(
            model_name='status',
            name='job_template',
            field=models.ManyToManyField(to='jobprogress.JobTemplate', verbose_name='Rodzaj Pracy'),
        ),
    ]
